package com.zack.shop.mvp.http.entity.ship;

import lombok.Getter;
import lombok.Setter;

/**
 * @Author 张迁-zhangqian
 * @Data 2018/6/19 上午10:32
 * @Package com.zack.shop.mvp.http.entity.ship
 **/

@Setter
@Getter
public class ShippingBean {

    private Integer id;

    /**
     * Database Column Remarks:
     * 用户id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.is_default
     *
     * @mbg.generated
     */
    private Integer isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * Database Column Remarks:
     * 收货姓名
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.receiver_name
     *
     * @mbg.generated
     */
    private String receiverName;

    /**
     * Database Column Remarks:
     * 收货固定电话
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.receiver_phone
     *
     * @mbg.generated
     */
    private String receiverPhone;

    /**
     * Database Column Remarks:
     * 收货移动电话
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.receiver_mobile
     *
     * @mbg.generated
     */
    private String receiverMobile;

    /**
     * Database Column Remarks:
     * 省份
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.receiver_province
     *
     * @mbg.generated
     */
    private String receiverProvince;

    /**
     * Database Column Remarks:
     * 城市
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.receiver_city
     *
     * @mbg.generated
     */
    private String receiverCity;

    /**
     * Database Column Remarks:
     * 区/县
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.receiver_district
     *
     * @mbg.generated
     */
    private String receiverDistrict;

    /**
     * Database Column Remarks:
     * 详细地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.receiver_address
     *
     * @mbg.generated
     */
    private String receiverAddress;

    /**
     * Database Column Remarks:
     * 邮编
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.receiver_zip
     *
     * @mbg.generated
     */
    private String receiverZip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zq_shipping.update_time
     *
     * @mbg.generated
     */
    private String updateTime;
}
